### PR TITLE
Add eth to tokens folder

### PR DESCRIPTION
**Pull request by emanuelgaspar**
`ewa` is trying to show this icon locally: 
<https://raw.githubusercontent.com/trakx/branding/dev/svg/tokens/eth.svg>

### CODE REVIEW

**Comment by monsieurleberre** [comment]
OK! I am not sure we should keep on duplicating the icons from the /constituents folder into the /tokens folder 🤔 (agree it is already the case with USDc)
It is not a big deal, but we are going to have 5 more soon https://trakx.atlassian.net/browse/TKX-1574
Instead do you think it is complicated to add that logic in `ewa`?

**Comment by emanuelgaspar** [comment]
> Instead do you think it is complicated to add that logic in `ewa`?

I believe we get the correct URL from <https://dev-api.trakx.io/peatio/public/currencies>
(Can't check now, API is unavailable)

I will try to fix the logic. Closing this PR.

**Comment by emanuelgaspar** [comment]
@monsieurleberre  We are getting <https://raw.githubusercontent.com/trakx/branding/dev/svg/tokens/eth.svg> from <https://dev-api.trakx.io/peatio/public/currencies>

How can we fix this?


```json
{
    "id": "eth",
    "name": "Ethereum",
    "description": null,
    "homepage": null,
    "price": "1.0",
    "explorer_transaction": "https://goerli.etherscan.io/tx/#{txid}",
    "explorer_address": "https://goerli.etherscan.io/address/#{address}",
    "type": "coin",
    "deposit_enabled": true,
    "withdrawal_enabled": false,
    "deposit_fee": "0.0",
    "min_deposit_amount": "0.00005",
    "withdraw_fee": "0.00005",
    "min_withdraw_amount": "0.00005",
    "withdraw_limit_24h": "0.0",
    "withdraw_limit_72h": "0.0",
    "base_factor": 1000000000000000000,
    "precision": 8,
    "position": 19,
    "icon_url": "https://raw.githubusercontent.com/trakx/branding/dev/svg/tokens/eth.svg",
    "min_confirmations": 1
}
```

**Comment by monsieurleberre** [comment]
Hello, sorry for the delay: you can simply change that with `tower` or the admin API of peatio.
https://dev-tower.trakx.io/exchange/currencies/eth/edit
I fixed it :)

**Pull request closed without merging**
